export const LEDGER_TRANSACTION_TYPE = {
  CONTRIBUTION: "CONTRIBUTION",
  LOAN_REPAYMENT: "LOAN_REPAYMENT",
  ABSENT_FINE: "ABSENT_FINE",
  SPECIAL_LOAN_FINE: "SPECIAL_LOAN_FINE",
  OTHER_INCOME: "OTHER_INCOME",
  BANK_DEPOSIT: "BANK_DEPOSIT",
  BANK_WITHDRAWAL: "BANK_WITHDRAWAL",
  OTHER_EXPENSE: "OTHER_EXPENSE",
  LOAN_DISBURSEMENT: "LOAN_DISBURSEMENT",
} as const;

export const LEDGER_TRANSACTION_TYPE_VALUES = Object.values(
  LEDGER_TRANSACTION_TYPE,
);

export type LedgerTransactionType =
  (typeof LEDGER_TRANSACTION_TYPE)[keyof typeof LEDGER_TRANSACTION_TYPE];