export const LEDGER_TRANSACTION_TYPE = {
  OPENING_BANK_BALANCE: "OPENING_BANK_BALANCE",
  OPENING_INVESTMENTS: "OPENING_INVESTMENTS",
  OPENING_CASH_IN_HAND: "OPENING_CASH_IN_HAND",
  OPENING_EXCESS_CORPUS: "OPENING_EXCESS_CORPUS",
  OPENING_CONTRIBUTION: "OPENING_CONTRIBUTION",
  OPENING_LOAN: "OPENING_LOAN",
  OPENING_SPECIAL_LOAN: "OPENING_SPECIAL_LOAN",
  CONTRIBUTION: "CONTRIBUTION",
  LOAN_REPAYMENT: "LOAN_REPAYMENT",
  ABSENT_FINE: "ABSENT_FINE",
  SPECIAL_LOAN_FINE: "SPECIAL_LOAN_FINE",
  OTHER_INCOME: "OTHER_INCOME",
  MEETING_INCOME_TOTAL: "MEETING_INCOME_TOTAL",
  BANK_DEPOSIT: "BANK_DEPOSIT",
  BANK_WITHDRAWAL: "BANK_WITHDRAWAL",
  BANK_INVESTMENT: "BANK_INVESTMENT",
  BANK_INVESTMENT_MATURITY: "BANK_INVESTMENT_MATURITY",
  BANK_INTEREST: "BANK_INTEREST",
  BANK_CHARGE: "BANK_CHARGE",
  OTHER_EXPENSE: "OTHER_EXPENSE",
  LOAN_DISBURSEMENT: "LOAN_DISBURSEMENT",
} as const;

export const LEDGER_TRANSACTION_TYPE_VALUES = Object.values(LEDGER_TRANSACTION_TYPE);

export type LedgerTransactionType =
  (typeof LEDGER_TRANSACTION_TYPE)[keyof typeof LEDGER_TRANSACTION_TYPE];

const OPENING_ACCOUNT_LEDGER_TYPES = new Set<LedgerTransactionType>([
  LEDGER_TRANSACTION_TYPE.OPENING_BANK_BALANCE,
  LEDGER_TRANSACTION_TYPE.OPENING_INVESTMENTS,
  LEDGER_TRANSACTION_TYPE.OPENING_EXCESS_CORPUS,
]);

const OPENING_MEMBER_LEDGER_TYPES = new Set<LedgerTransactionType>([
  LEDGER_TRANSACTION_TYPE.OPENING_CONTRIBUTION,
  LEDGER_TRANSACTION_TYPE.OPENING_LOAN,
  LEDGER_TRANSACTION_TYPE.OPENING_SPECIAL_LOAN,
]);

export function isOpeningAccountLedgerEntry(type: LedgerTransactionType): boolean {
  return OPENING_ACCOUNT_LEDGER_TYPES.has(type);
}

export function isOpeningMemberLedgerEntry(type: LedgerTransactionType): boolean {
  return OPENING_MEMBER_LEDGER_TYPES.has(type);
}
